// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from "./client";
import type {
  ListAgentsData,
  ListAgentsResponses,
  CreateAgentData,
  CreateAgentResponses,
  DeleteAgentData,
  DeleteAgentResponses,
  DeleteAgentErrors,
  GetAgentByIdData,
  GetAgentByIdResponses,
  GetAgentByIdErrors,
  UpdateAgentData,
  UpdateAgentResponses,
  UpdateAgentErrors,
  ListToolsData,
  ListToolsResponses,
  CreateToolData,
  CreateToolResponses,
  DeleteToolData,
  DeleteToolResponses,
  GetToolByIdData,
  GetToolByIdResponses,
  UpdateToolData,
  UpdateToolResponses,
  ListHumanTasksData,
  ListHumanTasksResponses,
  CreateHumanTaskData,
  CreateHumanTaskResponses,
  DeleteHumanTaskData,
  DeleteHumanTaskResponses,
  GetHumanTaskByIdData,
  GetHumanTaskByIdResponses,
  UpdateHumanTaskData,
  UpdateHumanTaskResponses,
  ResolveHumanTaskData,
  ResolveHumanTaskResponses,
  CreatePerformanceMetricData,
  CreatePerformanceMetricResponses,
  GetPerformanceMetricByQueryIdData,
  GetPerformanceMetricByQueryIdResponses,
  DeletePerformanceMetricData,
  DeletePerformanceMetricResponses,
  GetPerformanceMetricByIdData,
  GetPerformanceMetricByIdResponses,
  UpdatePerformanceMetricData,
  UpdatePerformanceMetricResponses,
  ListNotificationsData,
  ListNotificationsResponses,
  CreateNotificationData,
  CreateNotificationResponses,
  MarkAllNotificationsReadData,
  MarkAllNotificationsReadResponses,
  DeleteNotificationData,
  DeleteNotificationResponses,
  GetNotificationByIdData,
  GetNotificationByIdResponses,
  UpdateNotificationData,
  UpdateNotificationResponses,
  MarkNotificationReadData,
  MarkNotificationReadResponses,
  PostApiChatStreamData,
  PostApiChatStreamResponses,
} from "./types.gen";
import {
  listAgentsResponseTransformer,
  createAgentResponseTransformer,
  getAgentByIdResponseTransformer,
  updateAgentResponseTransformer,
} from "./transformers.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * List agents
 */
export const listAgents = <ThrowOnError extends boolean = false>(
  options: Options<ListAgentsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListAgentsResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: listAgentsResponseTransformer,
    responseType: "json",
    url: "/api/agents",
    ...options,
  });
};

/**
 * Create agent
 */
export const createAgent = <ThrowOnError extends boolean = false>(
  options: Options<CreateAgentData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateAgentResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: createAgentResponseTransformer,
    responseType: "json",
    url: "/api/agents",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete agent
 */
export const deleteAgent = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAgentData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteAgentResponses,
    DeleteAgentErrors,
    ThrowOnError
  >({
    url: "/api/agents/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get agent by ID
 */
export const getAgentById = <ThrowOnError extends boolean = false>(
  options: Options<GetAgentByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetAgentByIdResponses,
    GetAgentByIdErrors,
    ThrowOnError
  >({
    responseTransformer: getAgentByIdResponseTransformer,
    responseType: "json",
    url: "/api/agents/{id}",
    ...options,
  });
};

/**
 * Update agent
 */
export const updateAgent = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAgentData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateAgentResponses,
    UpdateAgentErrors,
    ThrowOnError
  >({
    responseTransformer: updateAgentResponseTransformer,
    responseType: "json",
    url: "/api/agents/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List tools
 */
export const listTools = <ThrowOnError extends boolean = false>(
  options?: Options<ListToolsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListToolsResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/tools",
    ...options,
  });
};

/**
 * Create tool
 */
export const createTool = <ThrowOnError extends boolean = false>(
  options: Options<CreateToolData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateToolResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/tools",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete tool
 */
export const deleteTool = <ThrowOnError extends boolean = false>(
  options: Options<DeleteToolData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteToolResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/tools/{id}",
    ...options,
  });
};

/**
 * Get tool
 */
export const getToolById = <ThrowOnError extends boolean = false>(
  options: Options<GetToolByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetToolByIdResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/tools/{id}",
    ...options,
  });
};

/**
 * Update tool
 */
export const updateTool = <ThrowOnError extends boolean = false>(
  options: Options<UpdateToolData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateToolResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/tools/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List human tasks
 */
export const listHumanTasks = <ThrowOnError extends boolean = false>(
  options?: Options<ListHumanTasksData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListHumanTasksResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/human-tasks",
    ...options,
  });
};

/**
 * Create human task
 */
export const createHumanTask = <ThrowOnError extends boolean = false>(
  options: Options<CreateHumanTaskData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateHumanTaskResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/human-tasks",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete human task
 */
export const deleteHumanTask = <ThrowOnError extends boolean = false>(
  options: Options<DeleteHumanTaskData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteHumanTaskResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/human-tasks/{id}",
    ...options,
  });
};

/**
 * Get human task
 */
export const getHumanTaskById = <ThrowOnError extends boolean = false>(
  options: Options<GetHumanTaskByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetHumanTaskByIdResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/human-tasks/{id}",
    ...options,
  });
};

/**
 * Update human task
 */
export const updateHumanTask = <ThrowOnError extends boolean = false>(
  options: Options<UpdateHumanTaskData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateHumanTaskResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/human-tasks/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Resolve human task
 */
export const resolveHumanTask = <ThrowOnError extends boolean = false>(
  options: Options<ResolveHumanTaskData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ResolveHumanTaskResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/human-tasks/{id}/resolve",
    ...options,
  });
};

/**
 * Create performance metric
 */
export const createPerformanceMetric = <ThrowOnError extends boolean = false>(
  options: Options<CreatePerformanceMetricData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreatePerformanceMetricResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/performance-metrics",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get metric by model query ID
 */
export const getPerformanceMetricByQueryId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetPerformanceMetricByQueryIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetPerformanceMetricByQueryIdResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/performance-metrics/by-query/{modelQueryId}",
    ...options,
  });
};

/**
 * Delete metric
 */
export const deletePerformanceMetric = <ThrowOnError extends boolean = false>(
  options: Options<DeletePerformanceMetricData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeletePerformanceMetricResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/performance-metrics/{id}",
    ...options,
  });
};

/**
 * Get metric by ID
 */
export const getPerformanceMetricById = <ThrowOnError extends boolean = false>(
  options: Options<GetPerformanceMetricByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetPerformanceMetricByIdResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/performance-metrics/{id}",
    ...options,
  });
};

/**
 * Update metric
 */
export const updatePerformanceMetric = <ThrowOnError extends boolean = false>(
  options: Options<UpdatePerformanceMetricData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdatePerformanceMetricResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/performance-metrics/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List notifications for user
 */
export const listNotifications = <ThrowOnError extends boolean = false>(
  options: Options<ListNotificationsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListNotificationsResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/notifications",
    ...options,
  });
};

/**
 * Create notification
 */
export const createNotification = <ThrowOnError extends boolean = false>(
  options: Options<CreateNotificationData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateNotificationResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/notifications",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Mark all notifications as read
 */
export const markAllNotificationsRead = <ThrowOnError extends boolean = false>(
  options?: Options<MarkAllNotificationsReadData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    MarkAllNotificationsReadResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/notifications/mark-all-read",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Delete notification
 */
export const deleteNotification = <ThrowOnError extends boolean = false>(
  options: Options<DeleteNotificationData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteNotificationResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/notifications/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get notification
 */
export const getNotificationById = <ThrowOnError extends boolean = false>(
  options: Options<GetNotificationByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetNotificationByIdResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/notifications/{id}",
    ...options,
  });
};

/**
 * Update notification
 */
export const updateNotification = <ThrowOnError extends boolean = false>(
  options: Options<UpdateNotificationData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateNotificationResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/notifications/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Mark notification as read
 */
export const markNotificationRead = <ThrowOnError extends boolean = false>(
  options: Options<MarkNotificationReadData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    MarkNotificationReadResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/notifications/{id}/read",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Send a message to an agent and get a streaming response
 */
export const postApiChatStream = <ThrowOnError extends boolean = false>(
  options: Options<PostApiChatStreamData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiChatStreamResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/chat/stream",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};
