// This file is auto-generated by @hey-api/openapi-ts

import type {
  ListAgentsResponse,
  CreateAgentResponse,
  GetAgentByIdResponse,
  UpdateAgentResponse,
} from "./types.gen";

const agentInstructionSchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt);
  }
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  return data;
};

const toolSchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt);
  }
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  return data;
};

const agentSchemaResponseTransformer = (data: any) => {
  if (data.createdAt) {
    data.createdAt = new Date(data.createdAt);
  }
  if (data.updatedAt) {
    data.updatedAt = new Date(data.updatedAt);
  }
  if (data.instructions) {
    data.instructions = data.instructions.map((item: any) => {
      return agentInstructionSchemaResponseTransformer(item);
    });
  }
  if (data.tools) {
    data.tools = data.tools.map((item: any) => {
      return toolSchemaResponseTransformer(item);
    });
  }
  return data;
};

export const listAgentsResponseTransformer = async (
  data: any,
): Promise<ListAgentsResponse> => {
  data = data.map((item: any) => {
    return agentSchemaResponseTransformer(item);
  });
  return data;
};

export const createAgentResponseTransformer = async (
  data: any,
): Promise<CreateAgentResponse> => {
  data = agentSchemaResponseTransformer(data);
  return data;
};

export const getAgentByIdResponseTransformer = async (
  data: any,
): Promise<GetAgentByIdResponse> => {
  data = agentSchemaResponseTransformer(data);
  return data;
};

export const updateAgentResponseTransformer = async (
  data: any,
): Promise<UpdateAgentResponse> => {
  data = agentSchemaResponseTransformer(data);
  return data;
};
