// This file is auto-generated by @hey-api/openapi-ts

export type Agent = {
  id?: string;
  userId?: string;
  name?: string;
  mode?: "PERFORMANCE" | "EFFICIENCY";
  createdAt?: Date;
  updatedAt?: Date;
  /**
   * Ordered instructions for this agent
   */
  instructions?: Array<AgentInstruction>;
  /**
   * Tools assigned to this agent
   */
  tools?: Array<Tool>;
};

export type AgentInstruction = {
  id?: string;
  agentId?: string;
  content?: string;
  order?: number;
  createdAt?: Date;
  updatedAt?: Date;
};

export type Tool = {
  id?: string;
  name?: string;
  createdAt?: Date;
  updatedAt?: Date;
};

export type ModelQuery = {
  id?: string;
  agentId?: string;
  userQuery?: string;
  modelResponse?: string | null;
  methodUsed?: "PERFORMANCE" | "EFFICIENCY";
  createdAt?: Date;
  updatedAt?: Date;
};

export type HumanTask = {
  id?: string;
  modelQueryId?: string;
  reason?: string;
  retrievedData?: string | null;
  modelMessage?: string;
  status?: "PENDING" | "RESOLVED";
  createdAt?: Date;
  updatedAt?: Date;
};

export type PerformanceMetric = {
  id?: string;
  modelQueryId?: string;
  tokenUsage?: number;
  responseTimeMs?: number | null;
  efficiencyScore?: number | null;
  qualityScore?: number | null;
  createdAt?: Date;
  updatedAt?: Date;
};

export type DailyStat = {
  id?: string;
  agentId?: string;
  date?: Date;
  totalQueries?: number;
  totalTokens?: number;
  avgEfficiency?: number | null;
  avgQuality?: number | null;
  createdAt?: Date;
  updatedAt?: Date;
};

export type Notification = {
  id?: string;
  userId?: string;
  type?: "HUMAN_TASK_CREATED" | "AGENT_ERROR" | "PERFORMANCE_ALERT" | "SYSTEM";
  title?: string;
  message?: string;
  isRead?: boolean;
  createdAt?: Date;
  updatedAt?: Date;
};

export type ListAgentsData = {
  body?: never;
  path?: never;
  query: {
    userId: string;
  };
  url: "/api/agents";
};

export type ListAgentsResponses = {
  /**
   * List of agents
   */
  200: Array<Agent>;
};

export type ListAgentsResponse = ListAgentsResponses[keyof ListAgentsResponses];

export type CreateAgentData = {
  body: {
    userId: string;
    name: string;
    mode?: "PERFORMANCE" | "EFFICIENCY";
    instructions?: Array<string>;
    tools?: Array<string>;
  };
  path?: never;
  query?: never;
  url: "/api/agents";
};

export type CreateAgentResponses = {
  /**
   * Created agent
   */
  201: Agent;
};

export type CreateAgentResponse =
  CreateAgentResponses[keyof CreateAgentResponses];

export type DeleteAgentData = {
  body: {
    userId: string;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/agents/{id}";
};

export type DeleteAgentErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type DeleteAgentResponses = {
  /**
   * Deleted
   */
  204: void;
};

export type DeleteAgentResponse =
  DeleteAgentResponses[keyof DeleteAgentResponses];

export type GetAgentByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/agents/{id}";
};

export type GetAgentByIdErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type GetAgentByIdResponses = {
  /**
   * Agent
   */
  200: Agent;
};

export type GetAgentByIdResponse =
  GetAgentByIdResponses[keyof GetAgentByIdResponses];

export type UpdateAgentData = {
  body: {
    userId: string;
    name?: string;
    mode?: "PERFORMANCE" | "EFFICIENCY";
    instructions?: Array<string>;
    tools?: Array<string>;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/agents/{id}";
};

export type UpdateAgentErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type UpdateAgentResponses = {
  /**
   * Updated agent
   */
  200: Agent;
};

export type UpdateAgentResponse =
  UpdateAgentResponses[keyof UpdateAgentResponses];

export type ListToolsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/tools";
};

export type ListToolsResponses = {
  /**
   * List of tools
   */
  200: unknown;
};

export type CreateToolData = {
  body: {
    name: string;
  };
  path?: never;
  query?: never;
  url: "/api/tools";
};

export type CreateToolResponses = {
  /**
   * Created tool
   */
  201: unknown;
};

export type DeleteToolData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/tools/{id}";
};

export type DeleteToolResponses = {
  /**
   * Deleted
   */
  204: void;
};

export type DeleteToolResponse = DeleteToolResponses[keyof DeleteToolResponses];

export type GetToolByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/tools/{id}";
};

export type GetToolByIdResponses = {
  /**
   * Tool
   */
  200: unknown;
};

export type UpdateToolData = {
  body?: {
    name?: string;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/tools/{id}";
};

export type UpdateToolResponses = {
  /**
   * Updated tool
   */
  200: unknown;
};

export type ListHumanTasksData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Only PENDING
     */
    pending?: boolean;
  };
  url: "/api/human-tasks";
};

export type ListHumanTasksResponses = {
  /**
   * List of human tasks
   */
  200: unknown;
};

export type CreateHumanTaskData = {
  body: {
    modelQueryId: string;
    reason: string;
    retrievedData?: string;
    modelMessage: string;
    status?: "PENDING" | "RESOLVED";
  };
  path?: never;
  query?: never;
  url: "/api/human-tasks";
};

export type CreateHumanTaskResponses = {
  /**
   * Created human task
   */
  201: unknown;
};

export type DeleteHumanTaskData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/human-tasks/{id}";
};

export type DeleteHumanTaskResponses = {
  /**
   * Deleted
   */
  204: void;
};

export type DeleteHumanTaskResponse =
  DeleteHumanTaskResponses[keyof DeleteHumanTaskResponses];

export type GetHumanTaskByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/human-tasks/{id}";
};

export type GetHumanTaskByIdResponses = {
  /**
   * Human task
   */
  200: unknown;
};

export type UpdateHumanTaskData = {
  body?: {
    reason?: string;
    retrievedData?: string;
    modelMessage?: string;
    status?: "PENDING" | "RESOLVED";
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/human-tasks/{id}";
};

export type UpdateHumanTaskResponses = {
  /**
   * Updated human task
   */
  200: unknown;
};

export type ResolveHumanTaskData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/human-tasks/{id}/resolve";
};

export type ResolveHumanTaskResponses = {
  /**
   * Resolved
   */
  200: unknown;
};

export type CreatePerformanceMetricData = {
  body: {
    modelQueryId: string;
    tokenUsage: number;
    responseTimeMs?: number;
    efficiencyScore?: number;
    qualityScore?: number;
  };
  path?: never;
  query?: never;
  url: "/api/performance-metrics";
};

export type CreatePerformanceMetricResponses = {
  /**
   * Created metric
   */
  201: unknown;
};

export type GetPerformanceMetricByQueryIdData = {
  body?: never;
  path: {
    modelQueryId: string;
  };
  query?: never;
  url: "/api/performance-metrics/by-query/{modelQueryId}";
};

export type GetPerformanceMetricByQueryIdResponses = {
  /**
   * Performance metric
   */
  200: unknown;
};

export type DeletePerformanceMetricData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/performance-metrics/{id}";
};

export type DeletePerformanceMetricResponses = {
  /**
   * Deleted
   */
  204: void;
};

export type DeletePerformanceMetricResponse =
  DeletePerformanceMetricResponses[keyof DeletePerformanceMetricResponses];

export type GetPerformanceMetricByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/performance-metrics/{id}";
};

export type GetPerformanceMetricByIdResponses = {
  /**
   * Performance metric
   */
  200: unknown;
};

export type UpdatePerformanceMetricData = {
  body?: {
    tokenUsage?: number;
    responseTimeMs?: number;
    efficiencyScore?: number;
    qualityScore?: number;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/performance-metrics/{id}";
};

export type UpdatePerformanceMetricResponses = {
  /**
   * Updated metric
   */
  200: unknown;
};

export type ListNotificationsData = {
  body?: never;
  path?: never;
  query: {
    userId: string;
    unread?: boolean;
  };
  url: "/api/notifications";
};

export type ListNotificationsResponses = {
  /**
   * List of notifications
   */
  200: unknown;
};

export type CreateNotificationData = {
  body: {
    userId: string;
    type: "HUMAN_TASK_CREATED" | "AGENT_ERROR" | "PERFORMANCE_ALERT" | "SYSTEM";
    title: string;
    message: string;
  };
  path?: never;
  query?: never;
  url: "/api/notifications";
};

export type CreateNotificationResponses = {
  /**
   * Created notification
   */
  201: unknown;
};

export type MarkAllNotificationsReadData = {
  body?: {
    userId: string;
  };
  path?: never;
  query?: never;
  url: "/api/notifications/mark-all-read";
};

export type MarkAllNotificationsReadResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type DeleteNotificationData = {
  body: {
    userId: string;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/notifications/{id}";
};

export type DeleteNotificationResponses = {
  /**
   * Deleted
   */
  204: void;
};

export type DeleteNotificationResponse =
  DeleteNotificationResponses[keyof DeleteNotificationResponses];

export type GetNotificationByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/notifications/{id}";
};

export type GetNotificationByIdResponses = {
  /**
   * Notification
   */
  200: unknown;
};

export type UpdateNotificationData = {
  body: {
    userId: string;
    title?: string;
    message?: string;
    isRead?: boolean;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/notifications/{id}";
};

export type UpdateNotificationResponses = {
  /**
   * Updated notification
   */
  200: unknown;
};

export type MarkNotificationReadData = {
  body: {
    userId: string;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/notifications/{id}/read";
};

export type MarkNotificationReadResponses = {
  /**
   * Updated notification
   */
  200: unknown;
};

export type PostApiChatStreamData = {
  body: {
    agentId: string;
    userId: string;
    message: string;
  };
  path?: never;
  query?: never;
  url: "/api/chat/stream";
};

export type PostApiChatStreamResponses = {
  /**
   * Streaming text response
   */
  200: unknown;
};

export type ClientOptions = {
  baseURL: "http://localhost:4200" | (string & {});
};
