// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options,
  listAgents,
  createAgent,
  deleteAgent,
  getAgentById,
  updateAgent,
  listTools,
  createTool,
  deleteTool,
  getToolById,
  updateTool,
  listHumanTasks,
  createHumanTask,
  deleteHumanTask,
  getHumanTaskById,
  updateHumanTask,
  resolveHumanTask,
  createPerformanceMetric,
  getPerformanceMetricByQueryId,
  deletePerformanceMetric,
  getPerformanceMetricById,
  updatePerformanceMetric,
  listNotifications,
  createNotification,
  markAllNotificationsRead,
  deleteNotification,
  getNotificationById,
  updateNotification,
  markNotificationRead,
  postApiChatStream,
} from "../sdk.gen";
import {
  queryOptions,
  type UseMutationOptions,
  type DefaultError,
} from "@tanstack/react-query";
import type {
  ListAgentsData,
  CreateAgentData,
  CreateAgentResponse,
  DeleteAgentData,
  DeleteAgentResponse,
  GetAgentByIdData,
  UpdateAgentData,
  UpdateAgentResponse,
  ListToolsData,
  CreateToolData,
  DeleteToolData,
  DeleteToolResponse,
  GetToolByIdData,
  UpdateToolData,
  ListHumanTasksData,
  CreateHumanTaskData,
  DeleteHumanTaskData,
  DeleteHumanTaskResponse,
  GetHumanTaskByIdData,
  UpdateHumanTaskData,
  ResolveHumanTaskData,
  CreatePerformanceMetricData,
  GetPerformanceMetricByQueryIdData,
  DeletePerformanceMetricData,
  DeletePerformanceMetricResponse,
  GetPerformanceMetricByIdData,
  UpdatePerformanceMetricData,
  ListNotificationsData,
  CreateNotificationData,
  MarkAllNotificationsReadData,
  DeleteNotificationData,
  DeleteNotificationResponse,
  GetNotificationByIdData,
  UpdateNotificationData,
  MarkNotificationReadData,
  PostApiChatStreamData,
} from "../types.gen";
import type { AxiosError } from "axios";
import { client as _heyApiClient } from "../client.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseURL" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL: (options?.client ?? _heyApiClient).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const listAgentsQueryKey = (options: Options<ListAgentsData>) =>
  createQueryKey("listAgents", options);

/**
 * List agents
 */
export const listAgentsOptions = (options: Options<ListAgentsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listAgents({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listAgentsQueryKey(options),
  });
};

export const createAgentQueryKey = (options: Options<CreateAgentData>) =>
  createQueryKey("createAgent", options);

/**
 * Create agent
 */
export const createAgentOptions = (options: Options<CreateAgentData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await createAgent({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: createAgentQueryKey(options),
  });
};

/**
 * Create agent
 */
export const createAgentMutation = (
  options?: Partial<Options<CreateAgentData>>,
): UseMutationOptions<
  CreateAgentResponse,
  AxiosError<DefaultError>,
  Options<CreateAgentData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateAgentResponse,
    AxiosError<DefaultError>,
    Options<CreateAgentData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await createAgent({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete agent
 */
export const deleteAgentMutation = (
  options?: Partial<Options<DeleteAgentData>>,
): UseMutationOptions<
  DeleteAgentResponse,
  AxiosError<DefaultError>,
  Options<DeleteAgentData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteAgentResponse,
    AxiosError<DefaultError>,
    Options<DeleteAgentData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteAgent({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getAgentByIdQueryKey = (options: Options<GetAgentByIdData>) =>
  createQueryKey("getAgentById", options);

/**
 * Get agent by ID
 */
export const getAgentByIdOptions = (options: Options<GetAgentByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAgentById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAgentByIdQueryKey(options),
  });
};

/**
 * Update agent
 */
export const updateAgentMutation = (
  options?: Partial<Options<UpdateAgentData>>,
): UseMutationOptions<
  UpdateAgentResponse,
  AxiosError<DefaultError>,
  Options<UpdateAgentData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateAgentResponse,
    AxiosError<DefaultError>,
    Options<UpdateAgentData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateAgent({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listToolsQueryKey = (options?: Options<ListToolsData>) =>
  createQueryKey("listTools", options);

/**
 * List tools
 */
export const listToolsOptions = (options?: Options<ListToolsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listTools({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listToolsQueryKey(options),
  });
};

export const createToolQueryKey = (options: Options<CreateToolData>) =>
  createQueryKey("createTool", options);

/**
 * Create tool
 */
export const createToolOptions = (options: Options<CreateToolData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await createTool({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: createToolQueryKey(options),
  });
};

/**
 * Create tool
 */
export const createToolMutation = (
  options?: Partial<Options<CreateToolData>>,
): UseMutationOptions<
  unknown,
  AxiosError<DefaultError>,
  Options<CreateToolData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<DefaultError>,
    Options<CreateToolData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await createTool({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete tool
 */
export const deleteToolMutation = (
  options?: Partial<Options<DeleteToolData>>,
): UseMutationOptions<
  DeleteToolResponse,
  AxiosError<DefaultError>,
  Options<DeleteToolData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteToolResponse,
    AxiosError<DefaultError>,
    Options<DeleteToolData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteTool({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getToolByIdQueryKey = (options: Options<GetToolByIdData>) =>
  createQueryKey("getToolById", options);

/**
 * Get tool
 */
export const getToolByIdOptions = (options: Options<GetToolByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getToolById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getToolByIdQueryKey(options),
  });
};

/**
 * Update tool
 */
export const updateToolMutation = (
  options?: Partial<Options<UpdateToolData>>,
): UseMutationOptions<
  unknown,
  AxiosError<DefaultError>,
  Options<UpdateToolData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<DefaultError>,
    Options<UpdateToolData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateTool({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listHumanTasksQueryKey = (options?: Options<ListHumanTasksData>) =>
  createQueryKey("listHumanTasks", options);

/**
 * List human tasks
 */
export const listHumanTasksOptions = (
  options?: Options<ListHumanTasksData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listHumanTasks({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listHumanTasksQueryKey(options),
  });
};

export const createHumanTaskQueryKey = (
  options: Options<CreateHumanTaskData>,
) => createQueryKey("createHumanTask", options);

/**
 * Create human task
 */
export const createHumanTaskOptions = (
  options: Options<CreateHumanTaskData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await createHumanTask({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: createHumanTaskQueryKey(options),
  });
};

/**
 * Create human task
 */
export const createHumanTaskMutation = (
  options?: Partial<Options<CreateHumanTaskData>>,
): UseMutationOptions<
  unknown,
  AxiosError<DefaultError>,
  Options<CreateHumanTaskData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<DefaultError>,
    Options<CreateHumanTaskData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await createHumanTask({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete human task
 */
export const deleteHumanTaskMutation = (
  options?: Partial<Options<DeleteHumanTaskData>>,
): UseMutationOptions<
  DeleteHumanTaskResponse,
  AxiosError<DefaultError>,
  Options<DeleteHumanTaskData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteHumanTaskResponse,
    AxiosError<DefaultError>,
    Options<DeleteHumanTaskData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteHumanTask({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getHumanTaskByIdQueryKey = (
  options: Options<GetHumanTaskByIdData>,
) => createQueryKey("getHumanTaskById", options);

/**
 * Get human task
 */
export const getHumanTaskByIdOptions = (
  options: Options<GetHumanTaskByIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getHumanTaskById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getHumanTaskByIdQueryKey(options),
  });
};

/**
 * Update human task
 */
export const updateHumanTaskMutation = (
  options?: Partial<Options<UpdateHumanTaskData>>,
): UseMutationOptions<
  unknown,
  AxiosError<DefaultError>,
  Options<UpdateHumanTaskData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<DefaultError>,
    Options<UpdateHumanTaskData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateHumanTask({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const resolveHumanTaskQueryKey = (
  options: Options<ResolveHumanTaskData>,
) => createQueryKey("resolveHumanTask", options);

/**
 * Resolve human task
 */
export const resolveHumanTaskOptions = (
  options: Options<ResolveHumanTaskData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await resolveHumanTask({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: resolveHumanTaskQueryKey(options),
  });
};

/**
 * Resolve human task
 */
export const resolveHumanTaskMutation = (
  options?: Partial<Options<ResolveHumanTaskData>>,
): UseMutationOptions<
  unknown,
  AxiosError<DefaultError>,
  Options<ResolveHumanTaskData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<DefaultError>,
    Options<ResolveHumanTaskData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await resolveHumanTask({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const createPerformanceMetricQueryKey = (
  options: Options<CreatePerformanceMetricData>,
) => createQueryKey("createPerformanceMetric", options);

/**
 * Create performance metric
 */
export const createPerformanceMetricOptions = (
  options: Options<CreatePerformanceMetricData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await createPerformanceMetric({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: createPerformanceMetricQueryKey(options),
  });
};

/**
 * Create performance metric
 */
export const createPerformanceMetricMutation = (
  options?: Partial<Options<CreatePerformanceMetricData>>,
): UseMutationOptions<
  unknown,
  AxiosError<DefaultError>,
  Options<CreatePerformanceMetricData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<DefaultError>,
    Options<CreatePerformanceMetricData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await createPerformanceMetric({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getPerformanceMetricByQueryIdQueryKey = (
  options: Options<GetPerformanceMetricByQueryIdData>,
) => createQueryKey("getPerformanceMetricByQueryId", options);

/**
 * Get metric by model query ID
 */
export const getPerformanceMetricByQueryIdOptions = (
  options: Options<GetPerformanceMetricByQueryIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPerformanceMetricByQueryId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPerformanceMetricByQueryIdQueryKey(options),
  });
};

/**
 * Delete metric
 */
export const deletePerformanceMetricMutation = (
  options?: Partial<Options<DeletePerformanceMetricData>>,
): UseMutationOptions<
  DeletePerformanceMetricResponse,
  AxiosError<DefaultError>,
  Options<DeletePerformanceMetricData>
> => {
  const mutationOptions: UseMutationOptions<
    DeletePerformanceMetricResponse,
    AxiosError<DefaultError>,
    Options<DeletePerformanceMetricData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deletePerformanceMetric({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getPerformanceMetricByIdQueryKey = (
  options: Options<GetPerformanceMetricByIdData>,
) => createQueryKey("getPerformanceMetricById", options);

/**
 * Get metric by ID
 */
export const getPerformanceMetricByIdOptions = (
  options: Options<GetPerformanceMetricByIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getPerformanceMetricById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getPerformanceMetricByIdQueryKey(options),
  });
};

/**
 * Update metric
 */
export const updatePerformanceMetricMutation = (
  options?: Partial<Options<UpdatePerformanceMetricData>>,
): UseMutationOptions<
  unknown,
  AxiosError<DefaultError>,
  Options<UpdatePerformanceMetricData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<DefaultError>,
    Options<UpdatePerformanceMetricData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updatePerformanceMetric({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listNotificationsQueryKey = (
  options: Options<ListNotificationsData>,
) => createQueryKey("listNotifications", options);

/**
 * List notifications for user
 */
export const listNotificationsOptions = (
  options: Options<ListNotificationsData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listNotifications({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listNotificationsQueryKey(options),
  });
};

export const createNotificationQueryKey = (
  options: Options<CreateNotificationData>,
) => createQueryKey("createNotification", options);

/**
 * Create notification
 */
export const createNotificationOptions = (
  options: Options<CreateNotificationData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await createNotification({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: createNotificationQueryKey(options),
  });
};

/**
 * Create notification
 */
export const createNotificationMutation = (
  options?: Partial<Options<CreateNotificationData>>,
): UseMutationOptions<
  unknown,
  AxiosError<DefaultError>,
  Options<CreateNotificationData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<DefaultError>,
    Options<CreateNotificationData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await createNotification({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const markAllNotificationsReadQueryKey = (
  options?: Options<MarkAllNotificationsReadData>,
) => createQueryKey("markAllNotificationsRead", options);

/**
 * Mark all notifications as read
 */
export const markAllNotificationsReadOptions = (
  options?: Options<MarkAllNotificationsReadData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await markAllNotificationsRead({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: markAllNotificationsReadQueryKey(options),
  });
};

/**
 * Mark all notifications as read
 */
export const markAllNotificationsReadMutation = (
  options?: Partial<Options<MarkAllNotificationsReadData>>,
): UseMutationOptions<
  unknown,
  AxiosError<DefaultError>,
  Options<MarkAllNotificationsReadData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<DefaultError>,
    Options<MarkAllNotificationsReadData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await markAllNotificationsRead({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete notification
 */
export const deleteNotificationMutation = (
  options?: Partial<Options<DeleteNotificationData>>,
): UseMutationOptions<
  DeleteNotificationResponse,
  AxiosError<DefaultError>,
  Options<DeleteNotificationData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteNotificationResponse,
    AxiosError<DefaultError>,
    Options<DeleteNotificationData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteNotification({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getNotificationByIdQueryKey = (
  options: Options<GetNotificationByIdData>,
) => createQueryKey("getNotificationById", options);

/**
 * Get notification
 */
export const getNotificationByIdOptions = (
  options: Options<GetNotificationByIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getNotificationById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getNotificationByIdQueryKey(options),
  });
};

/**
 * Update notification
 */
export const updateNotificationMutation = (
  options?: Partial<Options<UpdateNotificationData>>,
): UseMutationOptions<
  unknown,
  AxiosError<DefaultError>,
  Options<UpdateNotificationData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<DefaultError>,
    Options<UpdateNotificationData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateNotification({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const markNotificationReadQueryKey = (
  options: Options<MarkNotificationReadData>,
) => createQueryKey("markNotificationRead", options);

/**
 * Mark notification as read
 */
export const markNotificationReadOptions = (
  options: Options<MarkNotificationReadData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await markNotificationRead({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: markNotificationReadQueryKey(options),
  });
};

/**
 * Mark notification as read
 */
export const markNotificationReadMutation = (
  options?: Partial<Options<MarkNotificationReadData>>,
): UseMutationOptions<
  unknown,
  AxiosError<DefaultError>,
  Options<MarkNotificationReadData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<DefaultError>,
    Options<MarkNotificationReadData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await markNotificationRead({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const postApiChatStreamQueryKey = (
  options: Options<PostApiChatStreamData>,
) => createQueryKey("postApiChatStream", options);

/**
 * Send a message to an agent and get a streaming response
 */
export const postApiChatStreamOptions = (
  options: Options<PostApiChatStreamData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postApiChatStream({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postApiChatStreamQueryKey(options),
  });
};

/**
 * Send a message to an agent and get a streaming response
 */
export const postApiChatStreamMutation = (
  options?: Partial<Options<PostApiChatStreamData>>,
): UseMutationOptions<
  unknown,
  AxiosError<DefaultError>,
  Options<PostApiChatStreamData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    AxiosError<DefaultError>,
    Options<PostApiChatStreamData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postApiChatStream({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
