// This file is auto-generated by @hey-api/openapi-ts

export const AddToolBodySchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
  },
  type: "object",
  required: ["name"],
  title: "AddToolBody",
} as const;

export const AgentDetailResponseSchema = {
  properties: {
    agent_id: {
      type: "string",
      title: "Agent Id",
      description: "Agent ID (UUID)",
    },
    user_id: {
      type: "string",
      title: "User Id",
      description: "Owner user id",
    },
    name: {
      type: "string",
      title: "Name",
      description: "Display name",
    },
    mode: {
      $ref: "#/components/schemas/AgentMode",
      description: "PERFORMANCE | EFFICIENCY | BALANCED",
    },
    prompt: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Prompt",
      description: "System prompt",
    },
    instructions: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Instructions",
      description: "Instruction lines in order",
    },
    tools: {
      items: {
        $ref: "#/components/schemas/AgentToolRef",
      },
      type: "array",
      title: "Tools",
      description: "Tools linked to this agent (id, name)",
    },
    doc_count: {
      type: "integer",
      title: "Doc Count",
      description: "RAG document count for this agent",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
      description: "Creation time",
    },
    updated_at: {
      type: "string",
      format: "date-time",
      title: "Updated At",
      description: "Last update time",
    },
    metadata: {
      $ref: "#/components/schemas/AgentMetadata",
      description: "Metadata including status.indexing and status.enrich",
    },
  },
  type: "object",
  required: [
    "agent_id",
    "user_id",
    "name",
    "mode",
    "instructions",
    "doc_count",
    "created_at",
    "updated_at",
  ],
  title: "AgentDetailResponse",
  description: "Single agent full detail (GET /agents/{id}).",
} as const;

export const AgentInfoSchema = {
  properties: {
    agent_id: {
      type: "string",
      title: "Agent Id",
      description: "Agent ID (UUID)",
    },
    name: {
      type: "string",
      title: "Name",
      description: "Display name",
    },
    mode: {
      anyOf: [
        {
          $ref: "#/components/schemas/AgentMode",
        },
        {
          type: "null",
        },
      ],
      description: "PERFORMANCE | EFFICIENCY | BALANCED",
    },
    prompt: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Prompt",
      description: "System prompt",
    },
    instructions: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Instructions",
      description: "Instruction lines in order",
    },
    user: {
      anyOf: [
        {
          $ref: "#/components/schemas/UserRef",
        },
        {
          type: "null",
        },
      ],
      description: "Owner (when from DB)",
    },
    doc_count: {
      type: "integer",
      title: "Doc Count",
      description:
        "Number of documents in this agent's RAG index (when from DB)",
      default: 0,
    },
    tools: {
      items: {
        $ref: "#/components/schemas/AgentToolRef",
      },
      type: "array",
      title: "Tools",
      description: "Tools linked to this agent (id, name)",
    },
    created_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Created At",
      description: "Creation time (when from DB)",
    },
    updated_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Updated At",
      description: "Last update time (when from DB)",
    },
    metadata: {
      $ref: "#/components/schemas/AgentMetadata",
      description: "Metadata including status.indexing and status.enrich",
    },
  },
  type: "object",
  required: ["agent_id", "name"],
  title: "AgentInfo",
  description:
    "Single agent in list: agent_id, name, user ref; optional doc_count, metadata, timestamps, tools, instructions when from DB.",
} as const;

export const AgentMetadataSchema = {
  properties: {
    status: {
      $ref: "#/components/schemas/AgentStatusIndexing",
      description: "Status including indexing and enrich state",
    },
  },
  type: "object",
  title: "AgentMetadata",
  description:
    "Agent metadata; status.indexing (document) and status.enrich (prompt) state.",
} as const;

export const AgentModeSchema = {
  type: "string",
  enum: ["PERFORMANCE", "EFFICIENCY", "BALANCED"],
  title: "AgentMode",
  description: "Agent mode: PERFORMANCE | EFFICIENCY | BALANCED.",
} as const;

export const AgentStatusIndexingSchema = {
  properties: {
    indexing: {
      type: "string",
      title: "Indexing",
      description: "One of: pending, error, completed",
    },
    enrich: {
      type: "string",
      title: "Enrich",
      description: "One of: pending, error, completed",
      default: "pending",
    },
  },
  type: "object",
  required: ["indexing"],
  title: "AgentStatusIndexing",
  description: "Indexing and enrich status: pending | error | completed.",
} as const;

export const AgentToolRefSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
      description: "Tool ID (UUID)",
    },
    name: {
      type: "string",
      title: "Name",
      description: "Tool display name",
    },
  },
  type: "object",
  required: ["id", "name"],
  title: "AgentToolRef",
  description: "Tool reference in agent response (id and name).",
} as const;

export const Body_ingestDocumentSchema = {
  properties: {
    agent_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Agent Id",
      description: "Agent ID (UUID from app API)",
    },
    agent_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Agent Name",
      description: "Agent name (legacy)",
    },
    file: {
      type: "string",
      format: "binary",
      title: "File",
      description: "PDF, TXT, or DOCX file",
    },
  },
  type: "object",
  required: ["file"],
  title: "Body_ingestDocument",
} as const;

export const Body_uploadAndIndexSchema = {
  properties: {
    agent_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Agent Id",
      description: "Agent ID (UUID from app API)",
    },
    agent_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Agent Name",
      description: "Agent name (legacy)",
    },
    file: {
      type: "string",
      format: "binary",
      title: "File",
      description: "JSONL file",
    },
  },
  type: "object",
  required: ["file"],
  title: "Body_uploadAndIndex",
} as const;

export const ChatRequestSchema = {
  properties: {
    agent_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Agent Id",
      description:
        "Agent ID (UUID); when set, backend loads agent and builds system_prompt",
    },
    agent_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Agent Name",
      description:
        "Agent name (legacy; required when agent_id is not provided)",
    },
    message: {
      type: "string",
      title: "Message",
      description: "User message",
    },
    system_prompt: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "System Prompt",
      description:
        "Full system prompt including TOOLS line (legacy; required when agent_id is not provided)",
    },
  },
  type: "object",
  required: ["message"],
  title: "ChatRequest",
  description: `Request for streaming chat with 2-call router + generator.
When agent_id is set, backend loads agent and builds system_prompt; agent_name and system_prompt are optional.
When agent_id is not set (legacy), agent_name and system_prompt are required.`,
} as const;

export const CreateAgentRequestSchema = {
  properties: {
    user_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "User Id",
      description: "Owner user id (from auth; optional when under /api)",
    },
    name: {
      type: "string",
      title: "Name",
      description: "Display name",
    },
    mode: {
      type: "string",
      title: "Mode",
      description: "PERFORMANCE | EFFICIENCY | BALANCED",
      default: "EFFICIENCY",
    },
    prompt: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Prompt",
      description: "System prompt",
    },
    instructions: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Instructions",
      description: "Instruction lines",
    },
    tools: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Tools",
      description: "Tool names (e.g. RAG, Calculator)",
    },
  },
  type: "object",
  required: ["name"],
  title: "CreateAgentRequest",
  description:
    "Request to create an agent (stored in DB). Agent ID is always server-generated.",
} as const;

export const CreateApiTokenBodySchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    expires_in_days: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Expires In Days",
    },
  },
  type: "object",
  title: "CreateApiTokenBody",
} as const;

export const CreateHumanTaskBodySchema = {
  properties: {
    model_query_id: {
      type: "string",
      title: "Model Query Id",
    },
    reason: {
      type: "string",
      title: "Reason",
    },
    retrieved_data: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Retrieved Data",
    },
    model_message: {
      type: "string",
      title: "Model Message",
    },
    status: {
      type: "string",
      title: "Status",
      default: "PENDING",
    },
  },
  type: "object",
  required: ["model_query_id", "reason", "model_message"],
  title: "CreateHumanTaskBody",
} as const;

export const CreateToolBodySchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
  },
  type: "object",
  required: ["name"],
  title: "CreateToolBody",
} as const;

export const DocumentAddBodySchema = {
  properties: {
    id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Id",
    },
    content: {
      type: "string",
      title: "Content",
      default: "",
    },
    metadata: {
      anyOf: [
        {
          additionalProperties: true,
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Metadata",
    },
  },
  type: "object",
  title: "DocumentAddBody",
  description: "Add a single document to the agent's RAG index.",
} as const;

export const DocumentsIngestBodySchema = {
  properties: {
    filename: {
      type: "string",
      title: "Filename",
      default: "",
    },
    contentBase64: {
      type: "string",
      title: "Contentbase64",
      default: "",
    },
  },
  type: "object",
  title: "DocumentsIngestBody",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const HealthResponseSchema = {
  properties: {
    status: {
      type: "string",
      title: "Status",
      description: "Always 'healthy' when endpoint succeeds",
    },
    agents: {
      items: {
        type: "string",
      },
      type: "array",
      title: "Agents",
      description: "List of agent names with loaded RAG",
    },
    geminimesh_configured: {
      type: "boolean",
      title: "Geminimesh Configured",
      description: "Whether GeminiMesh API token is set",
    },
    embedding_model: {
      type: "string",
      title: "Embedding Model",
      description: "'loaded' or 'not_loaded'",
    },
    database_configured: {
      type: "boolean",
      title: "Database Configured",
      description: "Whether DATABASE_URL is set",
    },
    database_connected: {
      type: "boolean",
      title: "Database Connected",
      description: "Whether DB connection succeeds",
    },
  },
  type: "object",
  required: [
    "status",
    "agents",
    "geminimesh_configured",
    "embedding_model",
    "database_configured",
    "database_connected",
  ],
  title: "HealthResponse",
  description: "Health check response.",
} as const;

export const HumanTaskModelQueryRefSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
      description: "Model query ID",
    },
    userQuery: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Userquery",
      description: "User query text",
    },
    modelResponse: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Modelresponse",
      description: "Model response text",
    },
  },
  type: "object",
  required: ["id"],
  title: "HumanTaskModelQueryRef",
  description: "Model query reference embedded in a human task response.",
} as const;

export const HumanTaskResponseSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
      description: "Human task ID (UUID)",
    },
    modelQueryId: {
      type: "string",
      title: "Modelqueryid",
      description: "Linked model query ID",
    },
    reason: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Reason",
      description: "Reason for human review",
    },
    retrievedData: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Retrieveddata",
      description: "Retrieved data snapshot",
    },
    modelMessage: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Modelmessage",
      description: "Model message for context",
    },
    status: {
      type: "string",
      title: "Status",
      description: "PENDING | RESOLVED",
    },
    createdAt: {
      type: "string",
      title: "Createdat",
      description: "Creation time (ISO)",
    },
    updatedAt: {
      type: "string",
      title: "Updatedat",
      description: "Last update time (ISO)",
    },
    modelQuery: {
      anyOf: [
        {
          $ref: "#/components/schemas/HumanTaskModelQueryRef",
        },
        {
          type: "null",
        },
      ],
      description: "Linked model query when loaded",
    },
  },
  type: "object",
  required: ["id", "modelQueryId", "status", "createdAt", "updatedAt"],
  title: "HumanTaskResponse",
  description: "Single human task (list item or get-by-id).",
} as const;

export const InstructionCreateBodySchema = {
  properties: {
    content: {
      type: "string",
      title: "Content",
    },
    order: {
      type: "integer",
      title: "Order",
      default: 0,
    },
  },
  type: "object",
  required: ["content"],
  title: "InstructionCreateBody",
} as const;

export const InstructionUpdateBodySchema = {
  properties: {
    content: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Content",
    },
    order: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Order",
    },
  },
  type: "object",
  title: "InstructionUpdateBody",
} as const;

export const ListAgentsResponseSchema = {
  properties: {
    agents: {
      items: {
        $ref: "#/components/schemas/AgentInfo",
      },
      type: "array",
      title: "Agents",
      description: "Agents that have RAG data (from DATA_FOLDER)",
    },
    meta: {
      anyOf: [
        {
          $ref: "#/components/schemas/PaginationMeta",
        },
        {
          type: "null",
        },
      ],
      description: "Pagination metadata (when DB configured)",
    },
  },
  type: "object",
  required: ["agents"],
  title: "ListAgentsResponse",
  description: "Response for GET /agents: paginated agents with doc counts.",
} as const;

export const ListHumanTasksResponseSchema = {
  properties: {
    data: {
      items: {
        $ref: "#/components/schemas/HumanTaskResponse",
      },
      type: "array",
      title: "Data",
      description: "Human tasks",
    },
    meta: {
      $ref: "#/components/schemas/PaginationMeta",
      description: "Pagination metadata",
    },
  },
  type: "object",
  required: ["data", "meta"],
  title: "ListHumanTasksResponse",
  description: "Response for GET /human-tasks: paginated list of human tasks.",
} as const;

export const LoginBodySchema = {
  properties: {
    email: {
      type: "string",
      title: "Email",
    },
    password: {
      type: "string",
      title: "Password",
    },
  },
  type: "object",
  required: ["email", "password"],
  title: "LoginBody",
} as const;

export const ModelQueryCreateBodySchema = {
  properties: {
    user_query: {
      type: "string",
      title: "User Query",
    },
    model_response: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Model Response",
    },
    method_used: {
      type: "string",
      title: "Method Used",
      default: "EFFICIENCY",
    },
  },
  type: "object",
  required: ["user_query"],
  title: "ModelQueryCreateBody",
} as const;

export const ModelQueryUpdateBodySchema = {
  properties: {
    user_query: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "User Query",
    },
    model_response: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Model Response",
    },
    method_used: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Method Used",
    },
  },
  type: "object",
  title: "ModelQueryUpdateBody",
} as const;

export const PaginationMetaSchema = {
  properties: {
    page: {
      type: "integer",
      title: "Page",
      description: "Current page (1-based)",
    },
    limit: {
      type: "integer",
      title: "Limit",
      description: "Page size",
    },
    total: {
      type: "integer",
      title: "Total",
      description: "Total number of items",
    },
    pages: {
      type: "integer",
      title: "Pages",
      description: "Total number of pages",
    },
    more: {
      type: "boolean",
      title: "More",
      description: "Whether there are more pages",
    },
  },
  type: "object",
  required: ["page", "limit", "total", "pages", "more"],
  title: "PaginationMeta",
  description: "Pagination metadata for list endpoints.",
} as const;

export const RegisterBodySchema = {
  properties: {
    email: {
      type: "string",
      title: "Email",
    },
    password: {
      type: "string",
      title: "Password",
    },
    name: {
      type: "string",
      title: "Name",
      default: "",
    },
  },
  type: "object",
  required: ["email", "password"],
  title: "RegisterBody",
} as const;

export const UpdateAgentIndexRequestSchema = {
  properties: {
    agent_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Agent Id",
      description: "Agent ID (UUID from app API); use this or agent_name",
    },
    agent_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Agent Name",
      description: "Agent name (legacy); use this or agent_id",
    },
    action: {
      type: "string",
      title: "Action",
      description: "One of: add, update, delete",
    },
    doc_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Doc Id",
      description: "Document ID (required for delete)",
    },
    content: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Content",
      description: "JSON string with id, content, optional metadata",
    },
    metadata: {
      anyOf: [
        {
          additionalProperties: true,
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Metadata",
      description: "Optional metadata override",
    },
  },
  type: "object",
  required: ["action"],
  title: "UpdateAgentIndexRequest",
  description:
    "Request to add, update, or delete a document in an agent's RAG index.",
} as const;

export const UpdateAgentIndexResponseSchema = {
  properties: {
    status: {
      type: "string",
      title: "Status",
      description: "'success' on success",
    },
    total_docs: {
      type: "integer",
      title: "Total Docs",
      description: "Total documents in agent index after update",
    },
  },
  type: "object",
  required: ["status", "total_docs"],
  title: "UpdateAgentIndexResponse",
  description: "Response after updating agent RAG index (add/update/delete).",
} as const;

export const UpdateAgentRequestSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    mode: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Mode",
    },
    prompt: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Prompt",
    },
    instructions: {
      anyOf: [
        {
          items: {
            type: "string",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Instructions",
    },
    tools: {
      anyOf: [
        {
          items: {
            type: "string",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Tools",
    },
  },
  type: "object",
  title: "UpdateAgentRequest",
  description: "Request to update an agent (partial).",
} as const;

export const UpdateHumanTaskBodySchema = {
  properties: {
    reason: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Reason",
    },
    retrieved_data: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Retrieved Data",
    },
    model_message: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Model Message",
    },
    status: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Status",
    },
  },
  type: "object",
  title: "UpdateHumanTaskBody",
} as const;

export const UpdateToolBodySchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
  },
  type: "object",
  required: ["name"],
  title: "UpdateToolBody",
} as const;

export const UploadAndIndexResponseSchema = {
  properties: {
    status: {
      type: "string",
      title: "Status",
      description: "'success' on success",
    },
    docs_added: {
      type: "integer",
      title: "Docs Added",
      description: "Number of documents parsed and added",
    },
    total_docs: {
      type: "integer",
      title: "Total Docs",
      description: "Total documents in agent index after upload",
    },
  },
  type: "object",
  required: ["status", "docs_added", "total_docs"],
  title: "UploadAndIndexResponse",
  description: "Response after uploading a JSONL file and indexing documents.",
} as const;

export const UserReadSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
    },
    email: {
      type: "string",
      title: "Email",
    },
    name: {
      type: "string",
      title: "Name",
    },
    image: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Image",
    },
    email_verified: {
      type: "boolean",
      title: "Email Verified",
      default: false,
    },
  },
  type: "object",
  required: ["id", "email", "name"],
  title: "UserRead",
  description: "User as returned to frontend (e.g. GET /users/me).",
} as const;

export const UserRefSchema = {
  properties: {
    id: {
      type: "string",
      title: "Id",
      description: "User ID",
    },
    name: {
      type: "string",
      title: "Name",
      description: "Display name",
    },
  },
  type: "object",
  required: ["id", "name"],
  title: "UserRef",
  description: "Minimal user reference (id and name).",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
    input: {
      title: "Input",
    },
    ctx: {
      type: "object",
      title: "Context",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;

export const ModelQueryItemSchema = {
  type: "object",
  required: [
    "id",
    "agentId",
    "userQuery",
    "methodUsed",
    "createdAt",
    "updatedAt",
  ],
  properties: {
    id: {
      type: "string",
      description: "Model query ID (UUID)",
    },
    agentId: {
      type: "string",
      description: "Agent ID (UUID)",
    },
    userQuery: {
      type: "string",
      description: "User query text",
    },
    modelResponse: {
      type: "string",
      nullable: true,
      description: "Model response text",
    },
    methodUsed: {
      type: "string",
      description: "PERFORMANCE | EFFICIENCY",
    },
    flowLog: {
      type: "object",
      additionalProperties: true,
      nullable: true,
      description: "Request/response flow and metrics",
    },
    totalTokens: {
      type: "integer",
      nullable: true,
      description: "Total tokens used (generator)",
    },
    durationMs: {
      type: "integer",
      nullable: true,
      description: "Response duration in milliseconds",
    },
    createdAt: {
      type: "string",
      description: "Creation time (ISO)",
    },
    updatedAt: {
      type: "string",
      description: "Last update time (ISO)",
    },
  },
  title: "ModelQueryItem",
  description: "Single model query in list or get response",
} as const;

export const ListAgentQueriesResponseSchema = {
  type: "object",
  required: ["data", "meta"],
  properties: {
    data: {
      type: "array",
      items: {
        $ref: "#/components/schemas/ModelQueryItem",
      },
      description: "Model queries",
    },
    meta: {
      $ref: "#/components/schemas/PaginationMeta",
      description: "Pagination metadata",
    },
  },
  title: "ListAgentQueriesResponse",
  description: "Response for GET /api/agents/{agent_id}/queries",
} as const;

export const AgentStatRowSchema = {
  type: "object",
  required: ["id", "date", "totalQueries"],
  properties: {
    id: {
      type: "string",
      description: "Composite id: {agent_id}_{date}",
    },
    date: {
      type: "string",
      description: "Date (ISO)",
    },
    totalQueries: {
      type: "integer",
      description: "Number of queries that day",
    },
    totalTokens: {
      type: "integer",
      nullable: true,
      description: "Sum of tokens that day",
    },
    avgEfficiency: {
      type: "number",
      nullable: true,
      description: "Average response time (ms)",
    },
    avgQuality: {
      type: "number",
      nullable: true,
      description: "Average quality score",
    },
  },
  title: "AgentStatRow",
  description: "Single day aggregate for GET /api/agents/{agent_id}/stats",
} as const;

export const ListAgentStatsResponseSchema = {
  type: "object",
  required: ["data"],
  properties: {
    data: {
      type: "array",
      items: {
        $ref: "#/components/schemas/AgentStatRow",
      },
      description: "Daily stats",
    },
  },
  title: "ListAgentStatsResponse",
  description: "Response for GET /api/agents/{agent_id}/stats",
} as const;
