// This file is auto-generated by @hey-api/openapi-ts

export const PaginationMetaSchema = {
  type: "object",
  properties: {
    page: {
      type: "integer",
      description: "Current page",
    },
    limit: {
      type: "integer",
      description: "Page size",
    },
    total: {
      type: "integer",
      description: "Total number of items",
    },
    pages: {
      type: "integer",
      description: "Total number of pages available",
    },
    more: {
      type: "boolean",
      description: "True if there is at least one more page after this",
    },
  },
  required: ["page", "limit", "total", "pages", "more"],
} as const;

export const AgentSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    userId: {
      type: "string",
    },
    name: {
      type: "string",
    },
    mode: {
      type: "string",
      enum: ["PERFORMANCE", "EFFICIENCY", "BALANCED"],
    },
    prompt: {
      type: "string",
      nullable: true,
      description: "System prompt for the agent",
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    updatedAt: {
      type: "string",
      format: "date-time",
    },
    instructions: {
      type: "array",
      items: {
        $ref: "#/components/schemas/AgentInstruction",
      },
      description: "Ordered instructions for this agent",
    },
    tools: {
      type: "array",
      items: {
        $ref: "#/components/schemas/Tool",
      },
      description: "Tools assigned to this agent",
    },
  },
} as const;

export const AgentInstructionSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    agentId: {
      type: "string",
      format: "uuid",
    },
    content: {
      type: "string",
    },
    order: {
      type: "integer",
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    updatedAt: {
      type: "string",
      format: "date-time",
    },
  },
} as const;

export const ModelQuerySchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    agentId: {
      type: "string",
      format: "uuid",
    },
    userQuery: {
      type: "string",
    },
    modelResponse: {
      type: "string",
      nullable: true,
    },
    methodUsed: {
      type: "string",
      enum: ["PERFORMANCE", "EFFICIENCY"],
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    updatedAt: {
      type: "string",
      format: "date-time",
    },
  },
} as const;

export const DailyStatSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    agentId: {
      type: "string",
      format: "uuid",
    },
    date: {
      type: "string",
      format: "date",
    },
    totalQueries: {
      type: "integer",
    },
    totalTokens: {
      type: "integer",
    },
    avgEfficiency: {
      type: "number",
      nullable: true,
    },
    avgQuality: {
      type: "number",
      nullable: true,
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    updatedAt: {
      type: "string",
      format: "date-time",
    },
  },
} as const;

export const ToolSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    name: {
      type: "string",
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    updatedAt: {
      type: "string",
      format: "date-time",
    },
  },
} as const;

export const HumanTaskSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    modelQueryId: {
      type: "string",
      format: "uuid",
    },
    reason: {
      type: "string",
    },
    retrievedData: {
      type: "string",
      nullable: true,
    },
    modelMessage: {
      type: "string",
    },
    status: {
      type: "string",
      enum: ["PENDING", "RESOLVED"],
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    updatedAt: {
      type: "string",
      format: "date-time",
    },
  },
} as const;

export const PerformanceMetricSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    modelQueryId: {
      type: "string",
      format: "uuid",
    },
    tokenUsage: {
      type: "integer",
    },
    responseTimeMs: {
      type: "integer",
      nullable: true,
    },
    efficiencyScore: {
      type: "number",
      nullable: true,
    },
    qualityScore: {
      type: "number",
      nullable: true,
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    updatedAt: {
      type: "string",
      format: "date-time",
    },
  },
} as const;

export const NotificationSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    userId: {
      type: "string",
    },
    type: {
      type: "string",
      enum: [
        "HUMAN_TASK_CREATED",
        "AGENT_ERROR",
        "PERFORMANCE_ALERT",
        "SYSTEM",
      ],
    },
    title: {
      type: "string",
    },
    message: {
      type: "string",
    },
    isRead: {
      type: "boolean",
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
    updatedAt: {
      type: "string",
      format: "date-time",
    },
  },
} as const;

export const ApiTokenListItemSchema = {
  type: "object",
  description:
    "API token metadata (token value is never returned after creation)",
  properties: {
    id: {
      type: "string",
      format: "uuid",
    },
    name: {
      type: "string",
      nullable: true,
    },
    lastUsedAt: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
    expiresAt: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
    createdAt: {
      type: "string",
      format: "date-time",
    },
  },
} as const;

export const CreateApiTokenResponseSchema = {
  type: "object",
  description:
    "Response when creating an API token. The plain token is returned only once.",
  required: ["token", "id"],
  properties: {
    token: {
      type: "string",
      description:
        "Plain API token; store securely and use as Bearer token. Only returned once.",
    },
    id: {
      type: "string",
      format: "uuid",
    },
    name: {
      type: "string",
      nullable: true,
    },
    expiresAt: {
      type: "string",
      format: "date-time",
      nullable: true,
    },
  },
} as const;
