// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from "./client";
import type {
  ListAgentsData,
  ListAgentsResponses,
  CreateAgentData,
  CreateAgentResponses,
  DeleteAgentData,
  DeleteAgentResponses,
  DeleteAgentErrors,
  GetAgentByIdData,
  GetAgentByIdResponses,
  GetAgentByIdErrors,
  UpdateAgentData,
  UpdateAgentResponses,
  UpdateAgentErrors,
  ListAgentInstructionsData,
  ListAgentInstructionsResponses,
  CreateAgentInstructionData,
  CreateAgentInstructionResponses,
  CreateAgentInstructionErrors,
  DeleteAgentInstructionData,
  DeleteAgentInstructionResponses,
  DeleteAgentInstructionErrors,
  GetAgentInstructionByIdData,
  GetAgentInstructionByIdResponses,
  GetAgentInstructionByIdErrors,
  UpdateAgentInstructionData,
  UpdateAgentInstructionResponses,
  UpdateAgentInstructionErrors,
  IngestAgentDocumentData,
  IngestAgentDocumentResponses,
  IngestAgentDocumentErrors,
  ListAgentToolsData,
  ListAgentToolsResponses,
  AddAgentToolData,
  AddAgentToolResponses,
  AddAgentToolErrors,
  RemoveAgentToolData,
  RemoveAgentToolResponses,
  RemoveAgentToolErrors,
  ListAgentQueriesData,
  ListAgentQueriesResponses,
  CreateAgentQueryData,
  CreateAgentQueryResponses,
  CreateAgentQueryErrors,
  DeleteAgentQueryData,
  DeleteAgentQueryResponses,
  DeleteAgentQueryErrors,
  GetAgentQueryByIdData,
  GetAgentQueryByIdResponses,
  GetAgentQueryByIdErrors,
  UpdateAgentQueryData,
  UpdateAgentQueryResponses,
  UpdateAgentQueryErrors,
  ListAgentStatsData,
  ListAgentStatsResponses,
  CreateAgentStatData,
  CreateAgentStatResponses,
  CreateAgentStatErrors,
  GetAgentStatByDateData,
  GetAgentStatByDateResponses,
  GetAgentStatByDateErrors,
  DeleteAgentStatData,
  DeleteAgentStatResponses,
  DeleteAgentStatErrors,
  GetAgentStatByIdData,
  GetAgentStatByIdResponses,
  GetAgentStatByIdErrors,
  UpdateAgentStatData,
  UpdateAgentStatResponses,
  UpdateAgentStatErrors,
  ListToolsData,
  ListToolsResponses,
  CreateToolData,
  CreateToolResponses,
  DeleteToolData,
  DeleteToolResponses,
  GetToolByIdData,
  GetToolByIdResponses,
  UpdateToolData,
  UpdateToolResponses,
  ListHumanTasksData,
  ListHumanTasksResponses,
  CreateHumanTaskData,
  CreateHumanTaskResponses,
  DeleteHumanTaskData,
  DeleteHumanTaskResponses,
  GetHumanTaskByIdData,
  GetHumanTaskByIdResponses,
  UpdateHumanTaskData,
  UpdateHumanTaskResponses,
  ResolveHumanTaskData,
  ResolveHumanTaskResponses,
  CreatePerformanceMetricData,
  CreatePerformanceMetricResponses,
  GetPerformanceMetricByQueryIdData,
  GetPerformanceMetricByQueryIdResponses,
  DeletePerformanceMetricData,
  DeletePerformanceMetricResponses,
  GetPerformanceMetricByIdData,
  GetPerformanceMetricByIdResponses,
  UpdatePerformanceMetricData,
  UpdatePerformanceMetricResponses,
  ListNotificationsData,
  ListNotificationsResponses,
  MarkAllNotificationsReadData,
  MarkAllNotificationsReadResponses,
  GetNotificationByIdData,
  GetNotificationByIdResponses,
  MarkNotificationReadData,
  MarkNotificationReadResponses,
  ListApiTokensData,
  ListApiTokensResponses,
  CreateApiTokenData,
  CreateApiTokenResponses,
  RevokeApiTokenData,
  RevokeApiTokenResponses,
  RevokeApiTokenErrors,
  PostApiChatStreamData,
  PostApiChatStreamResponses,
} from "./types.gen";
import {
  listAgentsResponseTransformer,
  createAgentResponseTransformer,
  getAgentByIdResponseTransformer,
  updateAgentResponseTransformer,
  listAgentInstructionsResponseTransformer,
  createAgentInstructionResponseTransformer,
  getAgentInstructionByIdResponseTransformer,
  updateAgentInstructionResponseTransformer,
  listAgentToolsResponseTransformer,
  addAgentToolResponseTransformer,
  listAgentQueriesResponseTransformer,
  createAgentQueryResponseTransformer,
  getAgentQueryByIdResponseTransformer,
  updateAgentQueryResponseTransformer,
  listAgentStatsResponseTransformer,
  createAgentStatResponseTransformer,
  getAgentStatByDateResponseTransformer,
  getAgentStatByIdResponseTransformer,
  updateAgentStatResponseTransformer,
  listToolsResponseTransformer,
  listHumanTasksResponseTransformer,
  listNotificationsResponseTransformer,
  listApiTokensResponseTransformer,
  createApiTokenResponseTransformer,
} from "./transformers.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * List agents
 */
export const listAgents = <ThrowOnError extends boolean = false>(
  options?: Options<ListAgentsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListAgentsResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: listAgentsResponseTransformer,
    responseType: "json",
    url: "/api/agents",
    ...options,
  });
};

/**
 * Create agent
 */
export const createAgent = <ThrowOnError extends boolean = false>(
  options: Options<CreateAgentData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateAgentResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: createAgentResponseTransformer,
    responseType: "json",
    url: "/api/agents",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete agent
 */
export const deleteAgent = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAgentData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteAgentResponses,
    DeleteAgentErrors,
    ThrowOnError
  >({
    url: "/api/agents/{id}",
    ...options,
  });
};

/**
 * Get agent by ID
 */
export const getAgentById = <ThrowOnError extends boolean = false>(
  options: Options<GetAgentByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetAgentByIdResponses,
    GetAgentByIdErrors,
    ThrowOnError
  >({
    responseTransformer: getAgentByIdResponseTransformer,
    responseType: "json",
    url: "/api/agents/{id}",
    ...options,
  });
};

/**
 * Update agent
 */
export const updateAgent = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAgentData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateAgentResponses,
    UpdateAgentErrors,
    ThrowOnError
  >({
    responseTransformer: updateAgentResponseTransformer,
    responseType: "json",
    url: "/api/agents/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List instructions for an agent
 */
export const listAgentInstructions = <ThrowOnError extends boolean = false>(
  options: Options<ListAgentInstructionsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListAgentInstructionsResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: listAgentInstructionsResponseTransformer,
    responseType: "json",
    url: "/api/agents/{agentId}/instructions",
    ...options,
  });
};

/**
 * Create instruction for an agent
 */
export const createAgentInstruction = <ThrowOnError extends boolean = false>(
  options: Options<CreateAgentInstructionData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateAgentInstructionResponses,
    CreateAgentInstructionErrors,
    ThrowOnError
  >({
    responseTransformer: createAgentInstructionResponseTransformer,
    responseType: "json",
    url: "/api/agents/{agentId}/instructions",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete instruction
 */
export const deleteAgentInstruction = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAgentInstructionData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteAgentInstructionResponses,
    DeleteAgentInstructionErrors,
    ThrowOnError
  >({
    url: "/api/agents/{agentId}/instructions/{id}",
    ...options,
  });
};

/**
 * Get instruction by ID
 */
export const getAgentInstructionById = <ThrowOnError extends boolean = false>(
  options: Options<GetAgentInstructionByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetAgentInstructionByIdResponses,
    GetAgentInstructionByIdErrors,
    ThrowOnError
  >({
    responseTransformer: getAgentInstructionByIdResponseTransformer,
    responseType: "json",
    url: "/api/agents/{agentId}/instructions/{id}",
    ...options,
  });
};

/**
 * Update instruction
 */
export const updateAgentInstruction = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAgentInstructionData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateAgentInstructionResponses,
    UpdateAgentInstructionErrors,
    ThrowOnError
  >({
    responseTransformer: updateAgentInstructionResponseTransformer,
    responseType: "json",
    url: "/api/agents/{agentId}/instructions/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Ingest document for RAG
 * Upload a PDF, TXT, or DOCX file. Content is extracted to text, chunked, embedded, and added to the agent's RAG index.
 */
export const ingestAgentDocument = <ThrowOnError extends boolean = false>(
  options: Options<IngestAgentDocumentData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    IngestAgentDocumentResponses,
    IngestAgentDocumentErrors,
    ThrowOnError
  >({
    responseType: "json",
    url: "/api/agents/{agentId}/documents/ingest",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List tools assigned to an agent
 */
export const listAgentTools = <ThrowOnError extends boolean = false>(
  options: Options<ListAgentToolsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListAgentToolsResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: listAgentToolsResponseTransformer,
    responseType: "json",
    url: "/api/agents/{agentId}/tools",
    ...options,
  });
};

/**
 * Assign a tool to an agent
 */
export const addAgentTool = <ThrowOnError extends boolean = false>(
  options: Options<AddAgentToolData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    AddAgentToolResponses,
    AddAgentToolErrors,
    ThrowOnError
  >({
    responseTransformer: addAgentToolResponseTransformer,
    responseType: "json",
    url: "/api/agents/{agentId}/tools",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Remove tool assignment from an agent
 */
export const removeAgentTool = <ThrowOnError extends boolean = false>(
  options: Options<RemoveAgentToolData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    RemoveAgentToolResponses,
    RemoveAgentToolErrors,
    ThrowOnError
  >({
    url: "/api/agents/{agentId}/tools/{toolId}",
    ...options,
  });
};

/**
 * List model queries for an agent
 */
export const listAgentQueries = <ThrowOnError extends boolean = false>(
  options: Options<ListAgentQueriesData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListAgentQueriesResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: listAgentQueriesResponseTransformer,
    responseType: "json",
    url: "/api/agents/{agentId}/queries",
    ...options,
  });
};

/**
 * Create a model query for an agent
 */
export const createAgentQuery = <ThrowOnError extends boolean = false>(
  options: Options<CreateAgentQueryData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateAgentQueryResponses,
    CreateAgentQueryErrors,
    ThrowOnError
  >({
    responseTransformer: createAgentQueryResponseTransformer,
    responseType: "json",
    url: "/api/agents/{agentId}/queries",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete model query
 */
export const deleteAgentQuery = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAgentQueryData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteAgentQueryResponses,
    DeleteAgentQueryErrors,
    ThrowOnError
  >({
    url: "/api/agents/{agentId}/queries/{id}",
    ...options,
  });
};

/**
 * Get model query by ID
 */
export const getAgentQueryById = <ThrowOnError extends boolean = false>(
  options: Options<GetAgentQueryByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetAgentQueryByIdResponses,
    GetAgentQueryByIdErrors,
    ThrowOnError
  >({
    responseTransformer: getAgentQueryByIdResponseTransformer,
    responseType: "json",
    url: "/api/agents/{agentId}/queries/{id}",
    ...options,
  });
};

/**
 * Update model query
 */
export const updateAgentQuery = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAgentQueryData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateAgentQueryResponses,
    UpdateAgentQueryErrors,
    ThrowOnError
  >({
    responseTransformer: updateAgentQueryResponseTransformer,
    responseType: "json",
    url: "/api/agents/{agentId}/queries/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List daily stats for an agent
 */
export const listAgentStats = <ThrowOnError extends boolean = false>(
  options: Options<ListAgentStatsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    ListAgentStatsResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: listAgentStatsResponseTransformer,
    responseType: "json",
    url: "/api/agents/{agentId}/stats",
    ...options,
  });
};

/**
 * Create daily stat for an agent
 */
export const createAgentStat = <ThrowOnError extends boolean = false>(
  options: Options<CreateAgentStatData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateAgentStatResponses,
    CreateAgentStatErrors,
    ThrowOnError
  >({
    responseTransformer: createAgentStatResponseTransformer,
    responseType: "json",
    url: "/api/agents/{agentId}/stats",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get daily stat by agent and date
 */
export const getAgentStatByDate = <ThrowOnError extends boolean = false>(
  options: Options<GetAgentStatByDateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetAgentStatByDateResponses,
    GetAgentStatByDateErrors,
    ThrowOnError
  >({
    responseTransformer: getAgentStatByDateResponseTransformer,
    responseType: "json",
    url: "/api/agents/{agentId}/stats/date/{date}",
    ...options,
  });
};

/**
 * Delete daily stat
 */
export const deleteAgentStat = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAgentStatData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteAgentStatResponses,
    DeleteAgentStatErrors,
    ThrowOnError
  >({
    url: "/api/agents/{agentId}/stats/{id}",
    ...options,
  });
};

/**
 * Get daily stat by ID
 */
export const getAgentStatById = <ThrowOnError extends boolean = false>(
  options: Options<GetAgentStatByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetAgentStatByIdResponses,
    GetAgentStatByIdErrors,
    ThrowOnError
  >({
    responseTransformer: getAgentStatByIdResponseTransformer,
    responseType: "json",
    url: "/api/agents/{agentId}/stats/{id}",
    ...options,
  });
};

/**
 * Update daily stat
 */
export const updateAgentStat = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAgentStatData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateAgentStatResponses,
    UpdateAgentStatErrors,
    ThrowOnError
  >({
    responseTransformer: updateAgentStatResponseTransformer,
    responseType: "json",
    url: "/api/agents/{agentId}/stats/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List tools
 */
export const listTools = <ThrowOnError extends boolean = false>(
  options?: Options<ListToolsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListToolsResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: listToolsResponseTransformer,
    responseType: "json",
    url: "/api/tools",
    ...options,
  });
};

/**
 * Create tool
 */
export const createTool = <ThrowOnError extends boolean = false>(
  options: Options<CreateToolData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateToolResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/tools",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete tool
 */
export const deleteTool = <ThrowOnError extends boolean = false>(
  options: Options<DeleteToolData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteToolResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/tools/{id}",
    ...options,
  });
};

/**
 * Get tool
 */
export const getToolById = <ThrowOnError extends boolean = false>(
  options: Options<GetToolByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetToolByIdResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/tools/{id}",
    ...options,
  });
};

/**
 * Update tool
 */
export const updateTool = <ThrowOnError extends boolean = false>(
  options: Options<UpdateToolData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateToolResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/tools/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List human tasks
 */
export const listHumanTasks = <ThrowOnError extends boolean = false>(
  options?: Options<ListHumanTasksData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListHumanTasksResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: listHumanTasksResponseTransformer,
    responseType: "json",
    url: "/api/human-tasks",
    ...options,
  });
};

/**
 * Create human task
 */
export const createHumanTask = <ThrowOnError extends boolean = false>(
  options: Options<CreateHumanTaskData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreateHumanTaskResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/human-tasks",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Delete human task
 */
export const deleteHumanTask = <ThrowOnError extends boolean = false>(
  options: Options<DeleteHumanTaskData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteHumanTaskResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/human-tasks/{id}",
    ...options,
  });
};

/**
 * Get human task
 */
export const getHumanTaskById = <ThrowOnError extends boolean = false>(
  options: Options<GetHumanTaskByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetHumanTaskByIdResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/human-tasks/{id}",
    ...options,
  });
};

/**
 * Update human task
 */
export const updateHumanTask = <ThrowOnError extends boolean = false>(
  options: Options<UpdateHumanTaskData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdateHumanTaskResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/human-tasks/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Resolve human task
 */
export const resolveHumanTask = <ThrowOnError extends boolean = false>(
  options: Options<ResolveHumanTaskData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    ResolveHumanTaskResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/human-tasks/{id}/resolve",
    ...options,
  });
};

/**
 * Create performance metric
 */
export const createPerformanceMetric = <ThrowOnError extends boolean = false>(
  options: Options<CreatePerformanceMetricData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    CreatePerformanceMetricResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/performance-metrics",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get metric by model query ID
 */
export const getPerformanceMetricByQueryId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetPerformanceMetricByQueryIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetPerformanceMetricByQueryIdResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/performance-metrics/by-query/{modelQueryId}",
    ...options,
  });
};

/**
 * Delete metric
 */
export const deletePerformanceMetric = <ThrowOnError extends boolean = false>(
  options: Options<DeletePerformanceMetricData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeletePerformanceMetricResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/performance-metrics/{id}",
    ...options,
  });
};

/**
 * Get metric by ID
 */
export const getPerformanceMetricById = <ThrowOnError extends boolean = false>(
  options: Options<GetPerformanceMetricByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetPerformanceMetricByIdResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/performance-metrics/{id}",
    ...options,
  });
};

/**
 * Update metric
 */
export const updatePerformanceMetric = <ThrowOnError extends boolean = false>(
  options: Options<UpdatePerformanceMetricData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    UpdatePerformanceMetricResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/performance-metrics/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * List notifications
 */
export const listNotifications = <ThrowOnError extends boolean = false>(
  options?: Options<ListNotificationsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListNotificationsResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: listNotificationsResponseTransformer,
    responseType: "json",
    url: "/api/notifications",
    ...options,
  });
};

/**
 * Mark all notifications as read
 */
export const markAllNotificationsRead = <ThrowOnError extends boolean = false>(
  options?: Options<MarkAllNotificationsReadData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    MarkAllNotificationsReadResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/notifications/mark-all-read",
    ...options,
  });
};

/**
 * Get notification
 */
export const getNotificationById = <ThrowOnError extends boolean = false>(
  options: Options<GetNotificationByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetNotificationByIdResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/notifications/{id}",
    ...options,
  });
};

/**
 * Mark notification as read
 */
export const markNotificationRead = <ThrowOnError extends boolean = false>(
  options: Options<MarkNotificationReadData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    MarkNotificationReadResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/notifications/{id}/read",
    ...options,
  });
};

/**
 * List API tokens
 * List current user's API tokens (paginated). Token values are never returned.
 */
export const listApiTokens = <ThrowOnError extends boolean = false>(
  options?: Options<ListApiTokensData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    ListApiTokensResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: listApiTokensResponseTransformer,
    responseType: "json",
    url: "/api/api-tokens",
    ...options,
  });
};

/**
 * Create API token
 * Create an API token for the authenticated user. The plain token is returned only in this response; use it as Authorization: Bearer <token>.
 */
export const createApiToken = <ThrowOnError extends boolean = false>(
  options?: Options<CreateApiTokenData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    CreateApiTokenResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: createApiTokenResponseTransformer,
    responseType: "json",
    url: "/api/api-tokens",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  });
};

/**
 * Revoke API token
 */
export const revokeApiToken = <ThrowOnError extends boolean = false>(
  options: Options<RevokeApiTokenData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    RevokeApiTokenResponses,
    RevokeApiTokenErrors,
    ThrowOnError
  >({
    url: "/api/api-tokens/{id}",
    ...options,
  });
};

/**
 * Send a message to an agent and get a streaming response
 */
export const postApiChatStream = <ThrowOnError extends boolean = false>(
  options: Options<PostApiChatStreamData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostApiChatStreamResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/chat/stream",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};
