// This file is auto-generated by @hey-api/openapi-ts

import type { ListAgentsResponse2, CreateAgentResponse, GetAgentResponse, UpdateAgentResponse } from './types.gen';

const agentInfoSchemaResponseTransformer = (data: any) => {
    if (data.created_at) {
        data.created_at = new Date(data.created_at);
    }
    if (data.updated_at) {
        data.updated_at = new Date(data.updated_at);
    }
    return data;
};

const listAgentsResponseSchemaResponseTransformer = (data: any) => {
    data.agents = data.agents.map((item: any) => {
        return agentInfoSchemaResponseTransformer(item);
    });
    return data;
};

export const listAgentsResponseTransformer = async (data: any): Promise<ListAgentsResponse2> => {
    data = listAgentsResponseSchemaResponseTransformer(data);
    return data;
};

const agentDetailResponseSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    data.updated_at = new Date(data.updated_at);
    return data;
};

export const createAgentResponseTransformer = async (data: any): Promise<CreateAgentResponse> => {
    data = agentDetailResponseSchemaResponseTransformer(data);
    return data;
};

export const getAgentResponseTransformer = async (data: any): Promise<GetAgentResponse> => {
    data = agentDetailResponseSchemaResponseTransformer(data);
    return data;
};

export const updateAgentResponseTransformer = async (data: any): Promise<UpdateAgentResponse> => {
    data = agentDetailResponseSchemaResponseTransformer(data);
    return data;
};