// This file is auto-generated by @hey-api/openapi-ts

export type PaginationMeta = {
  /**
   * Current page
   */
  page: number;
  /**
   * Page size
   */
  limit: number;
  /**
   * Total number of items
   */
  total: number;
  /**
   * Total number of pages available
   */
  pages: number;
  /**
   * True if there is at least one more page after this
   */
  more: boolean;
};

export type Agent = {
  id?: string;
  userId?: string;
  name?: string;
  mode?: "PERFORMANCE" | "EFFICIENCY";
  /**
   * System prompt for the agent
   */
  prompt?: string | null;
  createdAt?: Date;
  updatedAt?: Date;
  /**
   * Ordered instructions for this agent
   */
  instructions?: Array<AgentInstruction>;
  /**
   * Tools assigned to this agent
   */
  tools?: Array<Tool>;
};

export type AgentInstruction = {
  id?: string;
  agentId?: string;
  content?: string;
  order?: number;
  createdAt?: Date;
  updatedAt?: Date;
};

export type ModelQuery = {
  id?: string;
  agentId?: string;
  userQuery?: string;
  modelResponse?: string | null;
  methodUsed?: "PERFORMANCE" | "EFFICIENCY";
  createdAt?: Date;
  updatedAt?: Date;
};

export type DailyStat = {
  id?: string;
  agentId?: string;
  date?: Date;
  totalQueries?: number;
  totalTokens?: number;
  avgEfficiency?: number | null;
  avgQuality?: number | null;
  createdAt?: Date;
  updatedAt?: Date;
};

export type Tool = {
  id?: string;
  name?: string;
  createdAt?: Date;
  updatedAt?: Date;
};

export type HumanTask = {
  id?: string;
  modelQueryId?: string;
  reason?: string;
  retrievedData?: string | null;
  modelMessage?: string;
  status?: "PENDING" | "RESOLVED";
  createdAt?: Date;
  updatedAt?: Date;
};

export type PerformanceMetric = {
  id?: string;
  modelQueryId?: string;
  tokenUsage?: number;
  responseTimeMs?: number | null;
  efficiencyScore?: number | null;
  qualityScore?: number | null;
  createdAt?: Date;
  updatedAt?: Date;
};

export type Notification = {
  id?: string;
  userId?: string;
  type?: "HUMAN_TASK_CREATED" | "AGENT_ERROR" | "PERFORMANCE_ALERT" | "SYSTEM";
  title?: string;
  message?: string;
  isRead?: boolean;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * API token metadata (token value is never returned after creation)
 */
export type ApiTokenListItem = {
  id?: string;
  name?: string | null;
  lastUsedAt?: Date | null;
  expiresAt?: Date | null;
  createdAt?: Date;
};

/**
 * Response when creating an API token. The plain token is returned only once.
 */
export type CreateApiTokenResponse = {
  /**
   * Plain API token; store securely and use as Bearer token. Only returned once.
   */
  token: string;
  id: string;
  name?: string | null;
  expiresAt?: Date | null;
};

export type ListAgentsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page (1-based)
     */
    page?: number;
    /**
     * Items per page (max 100)
     */
    limit?: number;
  };
  url: "/api/agents";
};

export type ListAgentsResponses = {
  /**
   * Paginated list of agents
   */
  200: {
    data: Array<Agent>;
    meta: {
      pagination?: PaginationMeta;
    };
  };
};

export type ListAgentsResponse = ListAgentsResponses[keyof ListAgentsResponses];

export type CreateAgentData = {
  body: {
    name: string;
    mode?: "PERFORMANCE" | "EFFICIENCY";
    /**
     * System prompt for the agent
     */
    prompt?: string | null;
    /**
     * Instruction IDs
     */
    instructions?: Array<string>;
    /**
     * Tool IDs
     */
    tools?: Array<string>;
  };
  path?: never;
  query?: never;
  url: "/api/agents";
};

export type CreateAgentResponses = {
  /**
   * Created agent
   */
  201: Agent;
};

export type CreateAgentResponse =
  CreateAgentResponses[keyof CreateAgentResponses];

export type DeleteAgentData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/agents/{id}";
};

export type DeleteAgentErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type DeleteAgentResponses = {
  /**
   * Deleted
   */
  204: void;
};

export type DeleteAgentResponse =
  DeleteAgentResponses[keyof DeleteAgentResponses];

export type GetAgentByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/agents/{id}";
};

export type GetAgentByIdErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type GetAgentByIdResponses = {
  /**
   * Agent
   */
  200: Agent;
};

export type GetAgentByIdResponse =
  GetAgentByIdResponses[keyof GetAgentByIdResponses];

export type UpdateAgentData = {
  body: {
    name?: string;
    mode?: "PERFORMANCE" | "EFFICIENCY";
    /**
     * System prompt for the agent
     */
    prompt?: string | null;
    /**
     * Instruction IDs
     */
    instructions?: Array<string>;
    /**
     * Tool IDs
     */
    tools?: Array<string>;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/agents/{id}";
};

export type UpdateAgentErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type UpdateAgentResponses = {
  /**
   * Updated agent
   */
  200: Agent;
};

export type UpdateAgentResponse =
  UpdateAgentResponses[keyof UpdateAgentResponses];

export type ListAgentInstructionsData = {
  body?: never;
  path: {
    agentId: string;
  };
  query?: {
    page?: number;
    limit?: number;
  };
  url: "/api/agents/{agentId}/instructions";
};

export type ListAgentInstructionsResponses = {
  /**
   * Paginated list of instructions
   */
  200: {
    data?: Array<AgentInstruction>;
    meta?: {
      pagination?: PaginationMeta;
    };
  };
};

export type ListAgentInstructionsResponse =
  ListAgentInstructionsResponses[keyof ListAgentInstructionsResponses];

export type CreateAgentInstructionData = {
  body: {
    content: string;
    order?: number;
  };
  path: {
    agentId: string;
  };
  query?: never;
  url: "/api/agents/{agentId}/instructions";
};

export type CreateAgentInstructionErrors = {
  /**
   * Agent not found
   */
  404: unknown;
};

export type CreateAgentInstructionResponses = {
  /**
   * Created instruction
   */
  201: AgentInstruction;
};

export type CreateAgentInstructionResponse =
  CreateAgentInstructionResponses[keyof CreateAgentInstructionResponses];

export type DeleteAgentInstructionData = {
  body?: never;
  path: {
    agentId: string;
    id: string;
  };
  query?: never;
  url: "/api/agents/{agentId}/instructions/{id}";
};

export type DeleteAgentInstructionErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type DeleteAgentInstructionResponses = {
  /**
   * Deleted
   */
  204: void;
};

export type DeleteAgentInstructionResponse =
  DeleteAgentInstructionResponses[keyof DeleteAgentInstructionResponses];

export type GetAgentInstructionByIdData = {
  body?: never;
  path: {
    agentId: string;
    id: string;
  };
  query?: never;
  url: "/api/agents/{agentId}/instructions/{id}";
};

export type GetAgentInstructionByIdErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type GetAgentInstructionByIdResponses = {
  /**
   * Instruction
   */
  200: AgentInstruction;
};

export type GetAgentInstructionByIdResponse =
  GetAgentInstructionByIdResponses[keyof GetAgentInstructionByIdResponses];

export type UpdateAgentInstructionData = {
  body?: {
    content?: string;
    order?: number;
  };
  path: {
    agentId: string;
    id: string;
  };
  query?: never;
  url: "/api/agents/{agentId}/instructions/{id}";
};

export type UpdateAgentInstructionErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type UpdateAgentInstructionResponses = {
  /**
   * Updated instruction
   */
  200: AgentInstruction;
};

export type UpdateAgentInstructionResponse =
  UpdateAgentInstructionResponses[keyof UpdateAgentInstructionResponses];

export type ListAgentToolsData = {
  body?: never;
  path: {
    agentId: string;
  };
  query?: {
    page?: number;
    limit?: number;
  };
  url: "/api/agents/{agentId}/tools";
};

export type ListAgentToolsResponses = {
  /**
   * Paginated list of tools
   */
  200: {
    data?: Array<Tool>;
    meta?: {
      pagination?: PaginationMeta;
    };
  };
};

export type ListAgentToolsResponse =
  ListAgentToolsResponses[keyof ListAgentToolsResponses];

export type AddAgentToolData = {
  body: {
    toolId: string;
  };
  path: {
    agentId: string;
  };
  query?: never;
  url: "/api/agents/{agentId}/tools";
};

export type AddAgentToolErrors = {
  /**
   * Agent or tool not found
   */
  404: unknown;
};

export type AddAgentToolResponses = {
  /**
   * Tool assigned
   */
  201: Tool;
};

export type AddAgentToolResponse =
  AddAgentToolResponses[keyof AddAgentToolResponses];

export type RemoveAgentToolData = {
  body?: never;
  path: {
    agentId: string;
    toolId: string;
  };
  query?: never;
  url: "/api/agents/{agentId}/tools/{toolId}";
};

export type RemoveAgentToolErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type RemoveAgentToolResponses = {
  /**
   * Removed
   */
  204: void;
};

export type RemoveAgentToolResponse =
  RemoveAgentToolResponses[keyof RemoveAgentToolResponses];

export type ListAgentQueriesData = {
  body?: never;
  path: {
    agentId: string;
  };
  query?: {
    page?: number;
    limit?: number;
  };
  url: "/api/agents/{agentId}/queries";
};

export type ListAgentQueriesResponses = {
  /**
   * Paginated list of model queries
   */
  200: {
    data?: Array<ModelQuery>;
    meta?: {
      pagination?: PaginationMeta;
    };
  };
};

export type ListAgentQueriesResponse =
  ListAgentQueriesResponses[keyof ListAgentQueriesResponses];

export type CreateAgentQueryData = {
  body: {
    userQuery: string;
    modelResponse?: string | null;
    methodUsed?: "PERFORMANCE" | "EFFICIENCY";
  };
  path: {
    agentId: string;
  };
  query?: never;
  url: "/api/agents/{agentId}/queries";
};

export type CreateAgentQueryErrors = {
  /**
   * Agent not found
   */
  404: unknown;
};

export type CreateAgentQueryResponses = {
  /**
   * Created model query
   */
  201: ModelQuery;
};

export type CreateAgentQueryResponse =
  CreateAgentQueryResponses[keyof CreateAgentQueryResponses];

export type DeleteAgentQueryData = {
  body?: never;
  path: {
    agentId: string;
    id: string;
  };
  query?: never;
  url: "/api/agents/{agentId}/queries/{id}";
};

export type DeleteAgentQueryErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type DeleteAgentQueryResponses = {
  /**
   * Deleted
   */
  204: void;
};

export type DeleteAgentQueryResponse =
  DeleteAgentQueryResponses[keyof DeleteAgentQueryResponses];

export type GetAgentQueryByIdData = {
  body?: never;
  path: {
    agentId: string;
    id: string;
  };
  query?: never;
  url: "/api/agents/{agentId}/queries/{id}";
};

export type GetAgentQueryByIdErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type GetAgentQueryByIdResponses = {
  /**
   * Model query
   */
  200: ModelQuery;
};

export type GetAgentQueryByIdResponse =
  GetAgentQueryByIdResponses[keyof GetAgentQueryByIdResponses];

export type UpdateAgentQueryData = {
  body?: {
    modelResponse?: string | null;
  };
  path: {
    agentId: string;
    id: string;
  };
  query?: never;
  url: "/api/agents/{agentId}/queries/{id}";
};

export type UpdateAgentQueryErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type UpdateAgentQueryResponses = {
  /**
   * Updated model query
   */
  200: ModelQuery;
};

export type UpdateAgentQueryResponse =
  UpdateAgentQueryResponses[keyof UpdateAgentQueryResponses];

export type ListAgentStatsData = {
  body?: never;
  path: {
    agentId: string;
  };
  query?: {
    /**
     * Start date (YYYY-MM-DD)
     */
    from?: Date;
    /**
     * End date (YYYY-MM-DD)
     */
    to?: Date;
    page?: number;
    limit?: number;
  };
  url: "/api/agents/{agentId}/stats";
};

export type ListAgentStatsResponses = {
  /**
   * Paginated list of daily stats
   */
  200: {
    data?: Array<DailyStat>;
    meta?: {
      pagination?: PaginationMeta;
    };
  };
};

export type ListAgentStatsResponse =
  ListAgentStatsResponses[keyof ListAgentStatsResponses];

export type CreateAgentStatData = {
  body: {
    date: Date;
    totalQueries: number;
    totalTokens: number;
    avgEfficiency?: number | null;
    avgQuality?: number | null;
  };
  path: {
    agentId: string;
  };
  query?: never;
  url: "/api/agents/{agentId}/stats";
};

export type CreateAgentStatErrors = {
  /**
   * Agent not found
   */
  404: unknown;
};

export type CreateAgentStatResponses = {
  /**
   * Created daily stat
   */
  201: DailyStat;
};

export type CreateAgentStatResponse =
  CreateAgentStatResponses[keyof CreateAgentStatResponses];

export type GetAgentStatByDateData = {
  body?: never;
  path: {
    agentId: string;
    /**
     * YYYY-MM-DD
     */
    date: string;
  };
  query?: never;
  url: "/api/agents/{agentId}/stats/date/{date}";
};

export type GetAgentStatByDateErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type GetAgentStatByDateResponses = {
  /**
   * Daily stat
   */
  200: DailyStat;
};

export type GetAgentStatByDateResponse =
  GetAgentStatByDateResponses[keyof GetAgentStatByDateResponses];

export type DeleteAgentStatData = {
  body?: never;
  path: {
    agentId: string;
    id: string;
  };
  query?: never;
  url: "/api/agents/{agentId}/stats/{id}";
};

export type DeleteAgentStatErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type DeleteAgentStatResponses = {
  /**
   * Deleted
   */
  204: void;
};

export type DeleteAgentStatResponse =
  DeleteAgentStatResponses[keyof DeleteAgentStatResponses];

export type GetAgentStatByIdData = {
  body?: never;
  path: {
    agentId: string;
    id: string;
  };
  query?: never;
  url: "/api/agents/{agentId}/stats/{id}";
};

export type GetAgentStatByIdErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type GetAgentStatByIdResponses = {
  /**
   * Daily stat
   */
  200: DailyStat;
};

export type GetAgentStatByIdResponse =
  GetAgentStatByIdResponses[keyof GetAgentStatByIdResponses];

export type UpdateAgentStatData = {
  body?: {
    totalQueries?: number;
    totalTokens?: number;
    avgEfficiency?: number | null;
    avgQuality?: number | null;
  };
  path: {
    agentId: string;
    id: string;
  };
  query?: never;
  url: "/api/agents/{agentId}/stats/{id}";
};

export type UpdateAgentStatErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type UpdateAgentStatResponses = {
  /**
   * Updated daily stat
   */
  200: DailyStat;
};

export type UpdateAgentStatResponse =
  UpdateAgentStatResponses[keyof UpdateAgentStatResponses];

export type ListToolsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page (1-based)
     */
    page?: number;
    /**
     * Items per page (max 100)
     */
    limit?: number;
  };
  url: "/api/tools";
};

export type ListToolsResponses = {
  /**
   * Paginated list of tools
   */
  200: {
    data: Array<Tool>;
    meta: {
      pagination?: PaginationMeta;
    };
  };
};

export type ListToolsResponse = ListToolsResponses[keyof ListToolsResponses];

export type CreateToolData = {
  body: {
    name: string;
  };
  path?: never;
  query?: never;
  url: "/api/tools";
};

export type CreateToolResponses = {
  /**
   * Created tool
   */
  201: unknown;
};

export type DeleteToolData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/tools/{id}";
};

export type DeleteToolResponses = {
  /**
   * Deleted
   */
  204: void;
};

export type DeleteToolResponse = DeleteToolResponses[keyof DeleteToolResponses];

export type GetToolByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/tools/{id}";
};

export type GetToolByIdResponses = {
  /**
   * Tool
   */
  200: unknown;
};

export type UpdateToolData = {
  body?: {
    name?: string;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/tools/{id}";
};

export type UpdateToolResponses = {
  /**
   * Updated tool
   */
  200: unknown;
};

export type ListHumanTasksData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Only PENDING
     */
    pending?: boolean;
    /**
     * Page (1-based)
     */
    page?: number;
    /**
     * Items per page (max 100)
     */
    limit?: number;
  };
  url: "/api/human-tasks";
};

export type ListHumanTasksResponses = {
  /**
   * Paginated list of human tasks
   */
  200: {
    data: Array<HumanTask>;
    meta: {
      pagination?: PaginationMeta;
    };
  };
};

export type ListHumanTasksResponse =
  ListHumanTasksResponses[keyof ListHumanTasksResponses];

export type CreateHumanTaskData = {
  body: {
    modelQueryId: string;
    reason: string;
    retrievedData?: string;
    modelMessage: string;
    status?: "PENDING" | "RESOLVED";
  };
  path?: never;
  query?: never;
  url: "/api/human-tasks";
};

export type CreateHumanTaskResponses = {
  /**
   * Created human task
   */
  201: unknown;
};

export type DeleteHumanTaskData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/human-tasks/{id}";
};

export type DeleteHumanTaskResponses = {
  /**
   * Deleted
   */
  204: void;
};

export type DeleteHumanTaskResponse =
  DeleteHumanTaskResponses[keyof DeleteHumanTaskResponses];

export type GetHumanTaskByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/human-tasks/{id}";
};

export type GetHumanTaskByIdResponses = {
  /**
   * Human task
   */
  200: unknown;
};

export type UpdateHumanTaskData = {
  body?: {
    reason?: string;
    retrievedData?: string;
    modelMessage?: string;
    status?: "PENDING" | "RESOLVED";
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/human-tasks/{id}";
};

export type UpdateHumanTaskResponses = {
  /**
   * Updated human task
   */
  200: unknown;
};

export type ResolveHumanTaskData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/human-tasks/{id}/resolve";
};

export type ResolveHumanTaskResponses = {
  /**
   * Resolved
   */
  200: unknown;
};

export type CreatePerformanceMetricData = {
  body: {
    modelQueryId: string;
    tokenUsage: number;
    responseTimeMs?: number;
    efficiencyScore?: number;
    qualityScore?: number;
  };
  path?: never;
  query?: never;
  url: "/api/performance-metrics";
};

export type CreatePerformanceMetricResponses = {
  /**
   * Created metric
   */
  201: unknown;
};

export type GetPerformanceMetricByQueryIdData = {
  body?: never;
  path: {
    modelQueryId: string;
  };
  query?: never;
  url: "/api/performance-metrics/by-query/{modelQueryId}";
};

export type GetPerformanceMetricByQueryIdResponses = {
  /**
   * Performance metric
   */
  200: unknown;
};

export type DeletePerformanceMetricData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/performance-metrics/{id}";
};

export type DeletePerformanceMetricResponses = {
  /**
   * Deleted
   */
  204: void;
};

export type DeletePerformanceMetricResponse =
  DeletePerformanceMetricResponses[keyof DeletePerformanceMetricResponses];

export type GetPerformanceMetricByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/performance-metrics/{id}";
};

export type GetPerformanceMetricByIdResponses = {
  /**
   * Performance metric
   */
  200: unknown;
};

export type UpdatePerformanceMetricData = {
  body?: {
    tokenUsage?: number;
    responseTimeMs?: number;
    efficiencyScore?: number;
    qualityScore?: number;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/performance-metrics/{id}";
};

export type UpdatePerformanceMetricResponses = {
  /**
   * Updated metric
   */
  200: unknown;
};

export type ListNotificationsData = {
  body?: never;
  path?: never;
  query?: {
    unread?: boolean;
    /**
     * Page (1-based)
     */
    page?: number;
    /**
     * Items per page (max 100)
     */
    limit?: number;
  };
  url: "/api/notifications";
};

export type ListNotificationsResponses = {
  /**
   * Paginated list of notifications
   */
  200: {
    data: Array<Notification>;
    meta: {
      pagination?: PaginationMeta;
    };
  };
};

export type ListNotificationsResponse =
  ListNotificationsResponses[keyof ListNotificationsResponses];

export type MarkAllNotificationsReadData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/notifications/mark-all-read";
};

export type MarkAllNotificationsReadResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetNotificationByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/notifications/{id}";
};

export type GetNotificationByIdResponses = {
  /**
   * Notification
   */
  200: unknown;
};

export type MarkNotificationReadData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/notifications/{id}/read";
};

export type MarkNotificationReadResponses = {
  /**
   * Updated notification
   */
  200: unknown;
};

export type ListApiTokensData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page (1-based)
     */
    page?: number;
    /**
     * Items per page (max 100)
     */
    limit?: number;
  };
  url: "/api/api-tokens";
};

export type ListApiTokensResponses = {
  /**
   * Paginated list of token metadata
   */
  200: {
    data: Array<ApiTokenListItem>;
    meta: {
      pagination?: PaginationMeta;
    };
  };
};

export type ListApiTokensResponse =
  ListApiTokensResponses[keyof ListApiTokensResponses];

export type CreateApiTokenData = {
  body?: {
    /**
     * Optional label (e.g. CI, Dashboard)
     */
    name?: string;
    /**
     * Optional expiry in days from now
     */
    expiresInDays?: number;
  };
  path?: never;
  query?: never;
  url: "/api/api-tokens";
};

export type CreateApiTokenResponses = {
  /**
   * Created token (plain token only returned once)
   */
  201: CreateApiTokenResponse;
};

export type CreateApiTokenResponse2 =
  CreateApiTokenResponses[keyof CreateApiTokenResponses];

export type RevokeApiTokenData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/api-tokens/{id}";
};

export type RevokeApiTokenErrors = {
  /**
   * Token not found
   */
  404: unknown;
};

export type RevokeApiTokenResponses = {
  /**
   * Token revoked
   */
  204: void;
};

export type RevokeApiTokenResponse =
  RevokeApiTokenResponses[keyof RevokeApiTokenResponses];

export type PostApiChatStreamData = {
  body: {
    agentId: string;
    message: string;
  };
  path?: never;
  query?: never;
  url: "/api/chat/stream";
};

export type PostApiChatStreamResponses = {
  /**
   * Streaming text response
   */
  200: unknown;
};

export type ClientOptions = {
  baseURL: "http://localhost:4200" | "http://localhost:4200" | (string & {});
};
